spring:
  cloud:
    stream:
      bindings:
        contentChannel:
          consumer:
            concurrency: 2
            maxAttempts: 3
          group: content-queue
          destination: content-exchange
      rabbit:
        bindings:
          contentChannel:
            consumer:
              exchangeType: topic
              autoBindDlq: true
              deadLetterQueueName: content-queue.dlq
              dlqDeadLetterExchange: content-dlq-exchange
              republishToDlq: true
              dlqTtl: 600000
      function:
        definition: contentChannelStreamFunction;
        bindings:
          contentChannelStreamFunction-in-0: contentChannel


configuration:
  body:
    size:
      # ignore pages bigger than this (bytes)
      max: 1067008
      # do not wait for a page more than (seconds)
  timeout: 10000
      # delete parsed content after 1 day
  expire: 1
  matcher-exchange: matcher-exchange